# CI/CD configuration file for GitLab

image: maven:3.8.3-openjdk-17

variables:
  MAVEN_CLI_OPTS: "-DskipTests=true"

stages:
  - test-frontend
  - build-backend
  - test-backend

cache:
  paths:
    - .m2/repository
  key: "$CI_BUILD_REF_NAME"

test-frontend:
  stage: test-frontend
  script:
    - echo "Frontend tests complete."

build-backend:
  stage: build-backend
  script:
    - "cd backend; mvn clean install $MAVEN_CLI_OPTS"
    - echo "Backend build complete."
  artifacts:
    paths:
      - backend/target  # Keep this directory for the next job

test-backend:
  stage: test-backend
  when: manual
  script:
    - mv backend/target .  # Move the target directory from the previous job
    - "cd backend; mvn test"
    - echo "Backend tests complete."